version: '3.1'

services:
  mariadb:
    image: mariadb:10.5.4
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: myStrongPassword
      MYSQL_DATABASE: test_crud
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    restart: always
    ports:
      - 3307:3306
    networks:
      - mariadb_network
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d


  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-app
    ports:
      - 3010:3010
    depends_on:
      - mariadb
    networks:
      - mariadb_network

    volumes:
      - ./config.yaml:/app/config.yaml

networks:
  mariadb_network:
    driver: bridge
